<a href="https://colab.research.google.com/github/Supu12-ui/DataScience/blob/main/Untitled25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 Create a pandas column using for loop

In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = {'student_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'test_score': [76, 88, 84, 67, 53, 96, 64, 91, 77, 73, 52, np.NaN]}
df = pd.DataFrame(raw_data, columns = ['student_name', 'test_score'])

In [4]:

grades = []
for row in df['test_score']:
    if row > 95:
        grades.append('A')
    elif row > 90:
        grades.append('A-')
    elif row > 85:
        grades.append('B')
    elif row > 80:
        grades.append('B-')
    elif row > 75:
        grades.append('C')
    elif row > 70:
        grades.append('C-')
    elif row > 65:
        grades.append('D')
    elif row > 60:
        grades.append('D-')
    else:
        grades.append('Failed')
df['grades'] = grades
df

   student_name  test_score  grades
0        Miller        76.0       C
1      Jacobson        88.0       B
2           Ali        84.0      B-
3        Milner        67.0       D
4         Cooze        53.0  Failed
5         Jacon        96.0       A
6        Ryaner        64.0      D-
7          Sone        91.0      A-
8         Sloan        77.0       C
9         Piger        73.0      C-
10        Riani        52.0  Failed
11          Ali         NaN  Failed

2 How To Get Column Names In Pandas Dataframe

In [5]:
df.columns

Index(['student_name', 'test_score', 'grades'], dtype='object')

3 How to rename columns in Pandas DataFrame

In [32]:
df.rename(columns = {'student_name':'student'}, inplace = True)
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
0,gp:AOqpTOESosHihRYEaaVhqopuBN4FS7_SwAvt0_ylrIt...,Dev Sureka,https://play-lh.googleusercontent.com/a/AATXAJ...,New still to have my first hit,4.00,0.00,5.261.1,2022-03-21 03:46:26,NaN,NaN
1,gp:AOqpTOFStXnqLETZVUPMw_Wu2hlS2G-by4EZx9tNag8...,Anthony Onochie,https://play-lh.googleusercontent.com/a/AATXAJ...,"Still works for me, no complaints. it's the pe...",5.00,0.00,5.259.0,2022-03-21 03:36:56,"Thanks for your kind words, Anthony. Your feed...",2022-03-01 09:05:29
2,gp:AOqpTOF5tlmhdjno2i1GK1aH8hfz5XDgsFNdZ7VtYgw...,Patricia Kilgore,https://play-lh.googleusercontent.com/a/AATXAJ...,Used to really like this app. It had alot of g...,1.00,0.00,5.261.1,2022-03-21 03:28:40,NaN,NaN
3,gp:AOqpTOGaVv5d8Vc5AQuATmNADU0oSD9ud2YT7AyzLBW...,Kadarius Player,https://play-lh.googleusercontent.com/a-/AOh14...,"Can't pay for anything, I've uninstalled and r...",1.00,0.00,5.261.1,2022-03-21 03:14:57,NaN,NaN
4,gp:AOqpTOEUuicqLSfZIkfhDORlE8Z8ilfDRWtDbSVM746...,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"Works great! Simple to use, fun! Really easy t...",5.00,0.00,5.260.0,2022-03-21 02:49:35,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
18405,gp:AOqpTOGLB58A_5cdvsQwfXh6kUbv-FCxKBEPGtrQ_LK...,Trish Mendoza,https://play-lh.googleusercontent.com/a/AATXAJ...,Is it really necessary to upgrade to premium w...,1.00,1.00,NaN,2021-08-06 23:52:10,"Hi Trish, we offer a few paid options that all...",2021-08-12 08:51:18
18406,gp:AOqpTOG8n5xt3jhqbTZhEIPsXCcTWbIHEkvgKkKctar...,BG Light,https://play-lh.googleusercontent.com/a/AATXAJ...,Everything about this dating app is money. Mos...,2.00,0.00,5.231.1,2021-08-06 23:41:22,"Hi there, thank you so much for giving us this...",2021-08-12 08:47:18
18407,gp:AOqpTOFKA0WgI805heNFV41rDq6Bc_BIUTbegD3BvZ5...,Stefan Hojnowski,https://play-lh.googleusercontent.com/a-/AOh14...,Never gets any better,1.00,2.00,5.230.0,2021-08-06 23:34:44,"Hi Stefan, we're sorry to hear you haven't had...",2021-08-12 08:46:48
18408,gp:AOqpTOFUSu8PVf1WSKxVulGTI1jbi0TgqfbowL-ilS3...,peter drozd,https://play-lh.googleusercontent.com/a-/AOh14...,You can't contact any women and they never pic...,1.00,1.00,5.228.1,2021-08-06 23:25:57,"Hi Peter, we're sorry to hear you haven't had ...",2021-08-12 08:48:18
18409,gp:AOqpTOFEOjoIe27v9UlAp8yz7Sl-cO5MaHvbLWLepG0...,Matthew Strickland,https://play-lh.googleusercontent.com/a/AATXAJyU4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

4 Collapse multiple Columns in Pandas

In [8]:
import pandas as pd
n = 3
Sample_1 = [57, 51, 6]
Sample_2 = [92, 16, 19]
Sample_3 = [15, 93, 71]
Sample_4 = [28, 73, 31]
  
sample_id = zip(["S"]*n, list(range(1, n + 1)))
  
s_names = [''.join([w[0], str(w[1])]) for w in sample_id]
  
d = {'s_names': s_names, 'Sample_1': Sample_1, 
     'Sample_2': Sample_2, 'Sample_3': Sample_3,
     'Sample_4': Sample_4}
  
df_1 = pd.DataFrame(d)
  
mapping = {'Sample_1': 'Result_1',
           'Sample_2': 'Result_1', 
           'Sample_3': 'Result_2', 
           'Sample_4': 'Result_2'}
  
df = df_1.set_index('s_names').groupby(mapping, axis = 1).sum()
  
df.reset_index(level = 0)

  s_names  Result_1  Result_2
0      S1       149        43
1      S2        67       166
2      S3        25       102

5 Get unique values from a column in Pandas     DataFrame

In [9]:
import pandas as pd
  
# create a dictionary with five fields each
data = {
    'A':['A1', 'A2', 'A3', 'A4', 'A5'], 
    'B':['B1', 'B2', 'B3', 'B4', 'B4'], 
    'C':['C1', 'C2', 'C3', 'C3', 'C3'], 
    'D':['D1', 'D2', 'D2', 'D2', 'D2'], 
    'E':['E1', 'E1', 'E1', 'E1', 'E1'] }
  
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data)
  
# Get the unique values of 'B' column
df.B.unique()

array(['B1', 'B2', 'B3', 'B4'], dtype=object)

6 Conditional operation on Pandas 
DataFrame columns

In [10]:
import pandas as pd
df = pd.DataFrame({'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/2011'],
                   'Product':['Umbrella', 'Matress', 'Badminton', 'Shuttle'],
                   'Last Price':[1200, 1500, 1600, 352],
                   'Updated Price':[1250, 1450, 1550, 400],
                   'Discount':[10, 10, 10, 10]})
print(df)

        Date    Product  Last Price  Updated Price  Discount
0  10/2/2011   Umbrella        1200           1250        10
1  11/2/2011    Matress        1500           1450        10
2  12/2/2011  Badminton        1600           1550        10
3  13/2/2011    Shuttle         352            400        10

In [11]:
import pandas as pd
df = pd.DataFrame({'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/2011'],
                   'Product':['Umbrella', 'Matress', 'Badminton', 'Shuttle'],
                   'Last_Price':[1200, 1500, 1600, 352],
                   'Updated_Price':[1250, 1450, 1550, 400],
                   'Discount':[10, 10, 10, 10]})
df.index =['Item 1', 'Item 2', 'Item 3', 'Item 4']
print(df)

             Date    Product  Last_Price  Updated_Price  Discount
Item 1  10/2/2011   Umbrella        1200           1250        10
Item 2  11/2/2011    Matress        1500           1450        10
Item 3  12/2/2011  Badminton        1600           1550        10
Item 4  13/2/2011    Shuttle         352            400        10

Return the Index label if some condition is satisfied over a column in Pandas DataframeUsing dictionary to remap values in Pandas DataFrame columns

In [14]:
Index_label = df[df['Updated_Price']>1000].index.tolist()
print(Index_label)

['Item 1', 'Item 2', 'Item 3']

Formatting integer column of Dataframe in Pandas

In [16]:
import pandas as pd
d = {'Quarters' : ['Quarter1','Quarter2','Quarter3','Quarter4'],
     'Revenue':[23400344.567,54363744.678,56789117.456,4132454.987]}
df=pd.DataFrame(d)
print(df)
pd.options.display.float_format = '{:.2f}'.format
print(df)

   Quarters       Revenue
0  Quarter1  2.340034e+07
1  Quarter2  5.436374e+07
2  Quarter3  5.678912e+07
3  Quarter4  4.132455e+06
   Quarters     Revenue
0  Quarter1 23400344.57
1  Quarter2 54363744.68
2  Quarter3 56789117.46
3  Quarter4  4132454.99

In [17]:
import pandas as pd
df = pd.DataFrame({'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/2011'],
                    'Event':['Music', 'Poetry', 'Theatre', 'Comedy'],
                    'Cost':[10000, 5000, 15000, 2000]})
print(df)

        Date    Event   Cost
0  10/2/2011    Music  10000
1  11/2/2011   Poetry   5000
2  12/2/2011  Theatre  15000
3  13/2/2011   Comedy   2000

In [18]:
df['Discounted_Price'] = df.apply(lambda row: row.Cost - 
                                  (row.Cost * 0.1), axis = 1)
print(df)

        Date    Event   Cost  Discounted_Price
0  10/2/2011    Music  10000           9000.00
1  11/2/2011   Poetry   5000           4500.00
2  12/2/2011  Theatre  15000          13500.00
3  13/2/2011   Comedy   2000           1800.00

Creating a Pandas dataframe column based on a given condition

In [19]:
import pandas as pd
df = pd.DataFrame({'Date' : ['11/8/2011', '11/9/2011', '11/10/2011',
                                        '11/11/2011', '11/12/2011'],
                'Event' : ['Music', 'Poetry', 'Music', 'Music', 'Poetry']})
print(df)

         Date   Event
0   11/8/2011   Music
1   11/9/2011  Poetry
2  11/10/2011   Music
3  11/11/2011   Music
4  11/12/2011  Poetry

In [20]:
df['Price'] = [1500 if x =='Music' else 800 for x in df['Event']]
print(df)

         Date   Event  Price
0   11/8/2011   Music   1500
1   11/9/2011  Poetry    800
2  11/10/2011   Music   1500
3  11/11/2011   Music   1500
4  11/12/2011  Poetry    800

Getting Unique values from a column in Pandas dataframe

In [21]:
import pandas as pd
data = {
    'A':['A1', 'A2', 'A3', 'A4', 'A5'], 
    'B':['B1', 'B2', 'B3', 'B4', 'B4'], 
    'C':['C1', 'C2', 'C3', 'C3', 'C3'], 
    'D':['D1', 'D2', 'D2', 'D2', 'D2'], 
    'E':['E1', 'E1', 'E1', 'E1', 'E1'] } 
df = pd.DataFrame(data)
df.B.unique()

array(['B1', 'B2', 'B3', 'B4'], dtype=object)

Split a String into columns using regex in pandas DataFrame

In [22]:
import pandas as pd
import re
movie_data = ["Name: The_Godfather Year: 1972 Rating: 9.2",
            "Name: Bird_Box Year: 2018 Rating: 6.8",
            "Name: Fight_Club Year: 1999 Rating: 8.8"]
movies = {"Name":[], "Year":[], "Rating":[]}
  
for item in movie_data:
    name_field = re.search("Name: .*",item)
      
    if name_field is not None:
        name = re.search('\w*\s\w*',name_field.group())
    else:
        name = None
    movies["Name"].append(name.group())
    year_field = re.search("Year: .*",item)
    if year_field is not None:
        year = re.search('\s\d\d\d\d',year_field.group())
    else:
        year = None
    movies["Year"].append(year.group().strip())
    rating_field = re.search("Rating: .*",item)
    if rating_field is not None: 
        rating = re.search('\s\d.\d',rating_field.group())
    else: 
        rating - None
    movies["Rating"].append(rating.group().strip())
df = pd.DataFrame(movies)
print(df)

             Name  Year Rating
0   The_Godfather  1972    9.2
1        Bird_Box  2018    6.8
2      Fight_Club  1999    8.8

Getting frequency counts of a columns in Pandas DataFrame

In [23]:
import pandas as pd
df = pd.DataFrame({'A': ['foo', 'bar', 'g2g', 'g2g', 'g2g',
                         'bar', 'bar', 'foo', 'bar'],
                  'B': ['a', 'b', 'a', 'b', 'b', 'b', 'a', 'a', 'b'] })
count = df['A'].value_counts()
print(count)

bar    4
g2g    3
foo    2
Name: A, dtype: int64

Change Data Type for one or more columns in Pandas Dataframe

In [24]:
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'c', 'd', 'e'],
    'C': [1.1, '1.0', '1.3', 2, 5] })
df = df.astype(str)
print(df.dtypes)

A    object
B    object
C    object
dtype: object

In [25]:
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'c', 'd', 'e'],
    'C': [1.1, '1.0', '1.3', 2, 5] })
convert_dict = {'A': int,
                'C': float
               }
  
df = df.astype(convert_dict)
print(df.dtypes)

A      int64
B     object
C    float64
dtype: object

Split a text column into two columns in Pandas DataFrame

In [26]:
import pandas as pd
df = pd.DataFrame({'Name': ['John Larter', 'Robert Junior', 'Jonny Depp'],
                   'Age':[32, 34, 36]})
   
print("Given Dataframe is :\n",df)
print("\nSplitting 'Name' column into two different columns :\n",
                                  df.Name.str.split(expand=True))

Given Dataframe is :
             Name  Age
0    John Larter   32
1  Robert Junior   34
2     Jonny Depp   36

Splitting 'Name' column into two different columns :
         0       1
0    John  Larter
1  Robert  Junior
2   Jonny    Depp

Difference of two columns in Pandas dataframe

In [27]:
import pandas as pd
df1 = { 'Name':['George','Andrea','micheal',
                'maggie','Ravi','Xien','Jalpa'],
        'score1':[62,47,55,74,32,77,86],
        'score2':[45,78,44,89,66,49,72]}
  
df1 = pd.DataFrame(df1,columns= ['Name','score1','score2'])
  
print("Given Dataframe :\n", df1)
df1['Score_diff'] = df1['score1'] - df1['score2']
print("\nDifference of score1 and score2 :\n", df1)

Given Dataframe :
       Name  score1  score2
0   George      62      45
1   Andrea      47      78
2  micheal      55      44
3   maggie      74      89
4     Ravi      32      66
5     Xien      77      49
6    Jalpa      86      72

Difference of score1 and score2 :
       Name  score1  score2  Score_diff
0   George      62      45          17
1   Andrea      47      78         -31
2  micheal      55      44          11
3   maggie      74      89         -15
4     Ravi      32      66         -34
5     Xien      77      49          28
6    Jalpa      86      72          14

Get the index of maximum value in DataFrame column

In [30]:
import pandas as pd
df = pd.read_csv("/content/bumble_google_play_reviews.csv")
 
df.head(10)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
0,gp:AOqpTOESosHihRYEaaVhqopuBN4FS7_SwAvt0_ylrIt...,Dev Sureka,https://play-lh.googleusercontent.com/a/AATXAJ...,New still to have my first hit,4.00,0.00,5.261.1,2022-03-21 03:46:26,NaN,NaN
1,gp:AOqpTOFStXnqLETZVUPMw_Wu2hlS2G-by4EZx9tNag8...,Anthony Onochie,https://play-lh.googleusercontent.com/a/AATXAJ...,"Still works for me, no complaints. it's the pe...",5.00,0.00,5.259.0,2022-03-21 03:36:56,"Thanks for your kind words, Anthony. Your feed...",2022-03-01 09:05:29
2,gp:AOqpTOF5tlmhdjno2i1GK1aH8hfz5XDgsFNdZ7VtYgw...,Patricia Kilgore,https://play-lh.googleusercontent.com/a/AATXAJ...,Used to really like this app. It had alot of g...,1.00,0.00,5.261.1,2022-03-21 03:28:40,NaN,NaN
3,gp:AOqpTOGaVv5d8Vc5AQuATmNADU0oSD9ud2YT7AyzLBW...,Kadarius Player,https://play-lh.googleusercontent.com/a-/AOh14...,"Can't pay for anything, I've uninstalled and r...",1.00,0.00,5.261.1,2022-03-21 03:14:57,NaN,NaN
4,gp:AOqpTOEUuicqLSfZIkfhDORlE8Z8ilfDRWtDbSVM746...,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"Works great! Simple to use, fun! Really easy t...",5.00,0.00,5.260.0,2022-03-21 02:49:35,NaN,NaN
5,gp:AOqpTOGhIDjV2fJeUs_Xn9DG5bWKosD-AIDNQojCymB...,Vaithis Pubathy,https://play-lh.googleusercontent.com/a/AATXAJ...,Ok,5.00,0.00,NaN,2022-03-21 02:48:51,NaN,NaN
6,gp:AOqpTOElhsY-D6DXAI2xDU3JuE-w-OA1aHMgmHBZWBO...,abdul nasir Al Mullah,https://play-lh.googleusercontent.com/a-/AOh14...,Wow amazing,5.00,0.00,5.261.1,2022-03-21 02:48:30,NaN,NaN
7,gp:AOqpTOH2Uu6412D9FDO_m-KikOKFZ_w4E_B2xrenglg...,Chad Bassman,https://play-lh.googleusercontent.com/a/AATXAJ...,Love it!,5.00,0.00,5.261.1,2022-03-21 02:39:36,NaN,NaN
8,gp:AOqpTOGTCC2DUaQyRIFjuQWyI_0-lOlM9mljmDE8kMF...,Umesh Chhabra,https://play-lh.googleusercontent.com/a-/AOh14...,Money hungry app,1.00,0.00,NaN,2022-03-21 02:27:07,NaN,NaN
9,gp:AOqpTOG2nrze42IR_vkmgXHK6FxpE52EdgmX7cHH8ih...,Meta,https://play-lh.googleusercontent.com/a-/AOh14...,"Easy to use, but I bought 1 week premium. Hard...",2.00,0.00,5.260.0,2022-03-21 02:26:34,NaN,NaN

In [31]:
df[['score']].idxmax()

score    1
dtype: int64

Get the index of minimum value in DataFrame column

In [33]:
df[['score']].idxmin()

score    2
dtype: int64

Get n-largest values from a particular column in Pandas DataFrame

In [34]:
df.nlargest(5, ['score'])

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
1,gp:AOqpTOFStXnqLETZVUPMw_Wu2hlS2G-by4EZx9tNag8...,Anthony Onochie,https://play-lh.googleusercontent.com/a/AATXAJ...,"Still works for me, no complaints. it's the pe...",5.00,0.00,5.259.0,2022-03-21 03:36:56,"Thanks for your kind words, Anthony. Your feed...",2022-03-01 09:05:29
4,gp:AOqpTOEUuicqLSfZIkfhDORlE8Z8ilfDRWtDbSVM746...,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"Works great! Simple to use, fun! Really easy t...",5.00,0.00,5.260.0,2022-03-21 02:49:35,NaN,NaN
5,gp:AOqpTOGhIDjV2fJeUs_Xn9DG5bWKosD-AIDNQojCymB...,Vaithis Pubathy,https://play-lh.googleusercontent.com/a/AATXAJ...,Ok,5.00,0.00,NaN,2022-03-21 02:48:51,NaN,NaN
6,gp:AOqpTOElhsY-D6DXAI2xDU3JuE-w-OA1aHMgmHBZWBO...,abdul nasir Al Mullah,https://play-lh.googleusercontent.com/a-/AOh14...,Wow amazing,5.00,0.00,5.261.1,2022-03-21 02:48:30,NaN,NaN
7,gp:AOqpTOH2Uu6412D9FDO_m-KikOKFZ_w4E_B2xrenglg...,Chad Bassman,https://play-lh.googleusercontent.com/a/AATXAJ...,Love it!,5.00,0.00,5.261.1,2022-03-21 02:39:36,NaN,NaN

Get n-smallest values from a particular column in Pandas DataFrame

In [35]:
df.nsmallest(5, ['score'])

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
2,gp:AOqpTOF5tlmhdjno2i1GK1aH8hfz5XDgsFNdZ7VtYgw...,Patricia Kilgore,https://play-lh.googleusercontent.com/a/AATXAJ...,Used to really like this app. It had alot of g...,1.00,0.00,5.261.1,2022-03-21 03:28:40,NaN,NaN
3,gp:AOqpTOGaVv5d8Vc5AQuATmNADU0oSD9ud2YT7AyzLBW...,Kadarius Player,https://play-lh.googleusercontent.com/a-/AOh14...,"Can't pay for anything, I've uninstalled and r...",1.00,0.00,5.261.1,2022-03-21 03:14:57,NaN,NaN
8,gp:AOqpTOGTCC2DUaQyRIFjuQWyI_0-lOlM9mljmDE8kMF...,Umesh Chhabra,https://play-lh.googleusercontent.com/a-/AOh14...,Money hungry app,1.00,0.00,NaN,2022-03-21 02:27:07,NaN,NaN
11,gp:AOqpTOH8e55ht_9za_qR48MIjiWJeA_msD7CUVmMM9Z...,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"Imagine charging people to use search filters,...",1.00,0.00,NaN,2022-03-21 01:45:08,NaN,NaN
13,gp:AOqpTOEgSoQzQvkusfa6RZXNGYvRiJzNMsWMLbX_Pff...,Emry Breedlove,https://play-lh.googleusercontent.com/a-/AOh14...,"Update, two years later: I installed recently,...",1.00,56.00,5.169.1,2022-03-21 01:27:52,NaN,NaN

How to drop one or multiple columns in Pandas Dataframe

In [37]:
df.drop(['reviewCreatedVersion'], axis = 1)

,reviewId,userName,userImage,content,score,thumbsUpCount,at,replyContent,repliedAt
0,gp:AOqpTOESosHihRYEaaVhqopuBN4FS7_SwAvt0_ylrIt...,Dev Sureka,https://play-lh.googleusercontent.com/a/AATXAJ...,New still to have my first hit,4.00,0.00,2022-03-21 03:46:26,NaN,NaN
1,gp:AOqpTOFStXnqLETZVUPMw_Wu2hlS2G-by4EZx9tNag8...,Anthony Onochie,https://play-lh.googleusercontent.com/a/AATXAJ...,"Still works for me, no complaints. it's the pe...",5.00,0.00,2022-03-21 03:36:56,"Thanks for your kind words, Anthony. Your feed...",2022-03-01 09:05:29
2,gp:AOqpTOF5tlmhdjno2i1GK1aH8hfz5XDgsFNdZ7VtYgw...,Patricia Kilgore,https://play-lh.googleusercontent.com/a/AATXAJ...,Used to really like this app. It had alot of g...,1.00,0.00,2022-03-21 03:28:40,NaN,NaN
3,gp:AOqpTOGaVv5d8Vc5AQuATmNADU0oSD9ud2YT7AyzLBW...,Kadarius Player,https://play-lh.googleusercontent.com/a-/AOh14...,"Can't pay for anything, I've uninstalled and r...",1.00,0.00,2022-03-21 03:14:57,NaN,NaN
4,gp:AOqpTOEUuicqLSfZIkfhDORlE8Z8ilfDRWtDbSVM746...,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"Works great! Simple to use, fun! Really easy t...",5.00,0.00,2022-03-21 02:49:35,NaN,NaN
...,...,...,...,...,...,...,...,...,...
18405,gp:AOqpTOGLB58A_5cdvsQwfXh6kUbv-FCxKBEPGtrQ_LK...,Trish Mendoza,https://play-lh.googleusercontent.com/a/AATXAJ...,Is it really necessary to upgrade to premium w...,1.00,1.00,2021-08-06 23:52:10,"Hi Trish, we offer a few paid options that all...",2021-08-12 08:51:18
18406,gp:AOqpTOG8n5xt3jhqbTZhEIPsXCcTWbIHEkvgKkKctar...,BG Light,https://play-lh.googleusercontent.com/a/AATXAJ...,Everything about this dating app is money. Mos...,2.00,0.00,2021-08-06 23:41:22,"Hi there, thank you so much for giving us this...",2021-08-12 08:47:18
18407,gp:AOqpTOFKA0WgI805heNFV41rDq6Bc_BIUTbegD3BvZ5...,Stefan Hojnowski,https://play-lh.googleusercontent.com/a-/AOh14...,Never gets any better,1.00,2.00,2021-08-06 23:34:44,"Hi Stefan, we're sorry to hear you haven't had...",2021-08-12 08:46:48
18408,gp:AOqpTOFUSu8PVf1WSKxVulGTI1jbi0TgqfbowL-ilS3...,peter drozd,https://play-lh.googleusercontent.com/a-/AOh14...,You can't contact any women and they never pic...,1.00,1.00,2021-08-06 23:25:57,"Hi Peter, we're sorry to hear you haven't had ...",2021-08-12 08:48:18
18409,gp:AOqpTOFEOjoIe27v9UlAp8yz7Sl-cO5MaHvbLWLepG0...,Matthew Strickland,https://play-lh.googleusercontent.com/a/AATXAJyU4,NaN,NaN,NaN,NaN,NaN,NaN

How to lowercase column names in Pandas dataframe

In [38]:
	
df= df.rename(columns=str.lower)

In [39]:
df

,reviewid,username,userimage,content,score,thumbsupcount,reviewcreatedversion,at,replycontent,repliedat
0,gp:AOqpTOESosHihRYEaaVhqopuBN4FS7_SwAvt0_ylrIt...,Dev Sureka,https://play-lh.googleusercontent.com/a/AATXAJ...,New still to have my first hit,4.00,0.00,5.261.1,2022-03-21 03:46:26,NaN,NaN
1,gp:AOqpTOFStXnqLETZVUPMw_Wu2hlS2G-by4EZx9tNag8...,Anthony Onochie,https://play-lh.googleusercontent.com/a/AATXAJ...,"Still works for me, no complaints. it's the pe...",5.00,0.00,5.259.0,2022-03-21 03:36:56,"Thanks for your kind words, Anthony. Your feed...",2022-03-01 09:05:29
2,gp:AOqpTOF5tlmhdjno2i1GK1aH8hfz5XDgsFNdZ7VtYgw...,Patricia Kilgore,https://play-lh.googleusercontent.com/a/AATXAJ...,Used to really like this app. It had alot of g...,1.00,0.00,5.261.1,2022-03-21 03:28:40,NaN,NaN
3,gp:AOqpTOGaVv5d8Vc5AQuATmNADU0oSD9ud2YT7AyzLBW...,Kadarius Player,https://play-lh.googleusercontent.com/a-/AOh14...,"Can't pay for anything, I've uninstalled and r...",1.00,0.00,5.261.1,2022-03-21 03:14:57,NaN,NaN
4,gp:AOqpTOEUuicqLSfZIkfhDORlE8Z8ilfDRWtDbSVM746...,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"Works great! Simple to use, fun! Really easy t...",5.00,0.00,5.260.0,2022-03-21 02:49:35,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
18405,gp:AOqpTOGLB58A_5cdvsQwfXh6kUbv-FCxKBEPGtrQ_LK...,Trish Mendoza,https://play-lh.googleusercontent.com/a/AATXAJ...,Is it really necessary to upgrade to premium w...,1.00,1.00,NaN,2021-08-06 23:52:10,"Hi Trish, we offer a few paid options that all...",2021-08-12 08:51:18
18406,gp:AOqpTOG8n5xt3jhqbTZhEIPsXCcTWbIHEkvgKkKctar...,BG Light,https://play-lh.googleusercontent.com/a/AATXAJ...,Everything about this dating app is money. Mos...,2.00,0.00,5.231.1,2021-08-06 23:41:22,"Hi there, thank you so much for giving us this...",2021-08-12 08:47:18
18407,gp:AOqpTOFKA0WgI805heNFV41rDq6Bc_BIUTbegD3BvZ5...,Stefan Hojnowski,https://play-lh.googleusercontent.com/a-/AOh14...,Never gets any better,1.00,2.00,5.230.0,2021-08-06 23:34:44,"Hi Stefan, we're sorry to hear you haven't had...",2021-08-12 08:46:48
18408,gp:AOqpTOFUSu8PVf1WSKxVulGTI1jbi0TgqfbowL-ilS3...,peter drozd,https://play-lh.googleusercontent.com/a-/AOh14...,You can't contact any women and they never pic...,1.00,1.00,5.228.1,2021-08-06 23:25:57,"Hi Peter, we're sorry to hear you haven't had ...",2021-08-12 08:48:18
18409,gp:AOqpTOFEOjoIe27v9UlAp8yz7Sl-cO5MaHvbLWLepG0...,Matthew Strickland,https://play-lh.googleusercontent.com/a/AATXAJyU4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Capitalize first letter of a column in Pandas dataframe

In [40]:
df['userimage'] = df['userimage'].str.capitalize()
  
df

,reviewid,username,userimage,content,score,thumbsupcount,reviewcreatedversion,at,replycontent,repliedat
0,gp:AOqpTOESosHihRYEaaVhqopuBN4FS7_SwAvt0_ylrIt...,Dev Sureka,Https://play-lh.googleusercontent.com/a/aatxaj...,New still to have my first hit,4.00,0.00,5.261.1,2022-03-21 03:46:26,NaN,NaN
1,gp:AOqpTOFStXnqLETZVUPMw_Wu2hlS2G-by4EZx9tNag8...,Anthony Onochie,Https://play-lh.googleusercontent.com/a/aatxaj...,"Still works for me, no complaints. it's the pe...",5.00,0.00,5.259.0,2022-03-21 03:36:56,"Thanks for your kind words, Anthony. Your feed...",2022-03-01 09:05:29
2,gp:AOqpTOF5tlmhdjno2i1GK1aH8hfz5XDgsFNdZ7VtYgw...,Patricia Kilgore,Https://play-lh.googleusercontent.com/a/aatxaj...,Used to really like this app. It had alot of g...,1.00,0.00,5.261.1,2022-03-21 03:28:40,NaN,NaN
3,gp:AOqpTOGaVv5d8Vc5AQuATmNADU0oSD9ud2YT7AyzLBW...,Kadarius Player,Https://play-lh.googleusercontent.com/a-/aoh14...,"Can't pay for anything, I've uninstalled and r...",1.00,0.00,5.261.1,2022-03-21 03:14:57,NaN,NaN
4,gp:AOqpTOEUuicqLSfZIkfhDORlE8Z8ilfDRWtDbSVM746...,A Google user,Https://play-lh.googleusercontent.com/egemoi2n...,"Works great! Simple to use, fun! Really easy t...",5.00,0.00,5.260.0,2022-03-21 02:49:35,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
18405,gp:AOqpTOGLB58A_5cdvsQwfXh6kUbv-FCxKBEPGtrQ_LK...,Trish Mendoza,Https://play-lh.googleusercontent.com/a/aatxaj...,Is it really necessary to upgrade to premium w...,1.00,1.00,NaN,2021-08-06 23:52:10,"Hi Trish, we offer a few paid options that all...",2021-08-12 08:51:18
18406,gp:AOqpTOG8n5xt3jhqbTZhEIPsXCcTWbIHEkvgKkKctar...,BG Light,Https://play-lh.googleusercontent.com/a/aatxaj...,Everything about this dating app is money. Mos...,2.00,0.00,5.231.1,2021-08-06 23:41:22,"Hi there, thank you so much for giving us this...",2021-08-12 08:47:18
18407,gp:AOqpTOFKA0WgI805heNFV41rDq6Bc_BIUTbegD3BvZ5...,Stefan Hojnowski,Https://play-lh.googleusercontent.com/a-/aoh14...,Never gets any better,1.00,2.00,5.230.0,2021-08-06 23:34:44,"Hi Stefan, we're sorry to hear you haven't had...",2021-08-12 08:46:48
18408,gp:AOqpTOFUSu8PVf1WSKxVulGTI1jbi0TgqfbowL-ilS3...,peter drozd,Https://play-lh.googleusercontent.com/a-/aoh14...,You can't contact any women and they never pic...,1.00,1.00,5.228.1,2021-08-06 23:25:57,"Hi Peter, we're sorry to hear you haven't had ...",2021-08-12 08:48:18
18409,gp:AOqpTOFEOjoIe27v9UlAp8yz7Sl-cO5MaHvbLWLepG0...,Matthew Strickland,Https://play-lh.googleusercontent.com/a/aatxajyu4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df['username'] = df['username'].str.upper()
  
df.head()

,reviewid,username,userimage,content,score,thumbsupcount,reviewcreatedversion,at,replycontent,repliedat
0,gp:AOqpTOESosHihRYEaaVhqopuBN4FS7_SwAvt0_ylrIt...,DEV SUREKA,Https://play-lh.googleusercontent.com/a/aatxaj...,New still to have my first hit,4.00,0.00,5.261.1,2022-03-21 03:46:26,NaN,NaN
1,gp:AOqpTOFStXnqLETZVUPMw_Wu2hlS2G-by4EZx9tNag8...,ANTHONY ONOCHIE,Https://play-lh.googleusercontent.com/a/aatxaj...,"Still works for me, no complaints. it's the pe...",5.00,0.00,5.259.0,2022-03-21 03:36:56,"Thanks for your kind words, Anthony. Your feed...",2022-03-01 09:05:29
2,gp:AOqpTOF5tlmhdjno2i1GK1aH8hfz5XDgsFNdZ7VtYgw...,PATRICIA KILGORE,Https://play-lh.googleusercontent.com/a/aatxaj...,Used to really like this app. It had alot of g...,1.00,0.00,5.261.1,2022-03-21 03:28:40,NaN,NaN
3,gp:AOqpTOGaVv5d8Vc5AQuATmNADU0oSD9ud2YT7AyzLBW...,KADARIUS PLAYER,Https://play-lh.googleusercontent.com/a-/aoh14...,"Can't pay for anything, I've uninstalled and r...",1.00,0.00,5.261.1,2022-03-21 03:14:57,NaN,NaN
4,gp:AOqpTOEUuicqLSfZIkfhDORlE8Z8ilfDRWtDbSVM746...,A GOOGLE USER,Https://play-lh.googleusercontent.com/egemoi2n...,"Works great! Simple to use, fun! Really easy t...",5.00,0.00,5.260.0,2022-03-21 02:49:35,NaN,NaN